### ISSUE TITLE
The chart is not interactive and not large enough

### ISSUE THREAD

**Issue by jiyinyiyong** [edebill/modulecounts#13]
As I hover my mouse on one curve, I cannot tell which is which, not hints, not active state as the list left, nothing happens.

I tried [one](http://repo.tiye.me/pkgs-constract/) before but didn't got so much data. It's quite nice to see it putting togather.

**Comment by JesseAldridge** [comment]
This could be done with D3:  https://bl.ocks.org/mbostock/8033015

I've found D3 to be a lot harder to understand than flot though.
