### ISSUE TITLE
CRAN module count different from crantastic

### ISSUE THREAD

**Issue by nuest** [edebill/modulecounts#25]
Hi guys. Great site! Just wanted to point out that your count of R packages differs from the one at crantastic (http://crantastic.org/packages) - maybe that is a good secondary source.

**Comment by edebill** [comment]
Oh, cool. Looks like crantastic might be superseding cran.r-project.org as
the best R repository. Very cool. I think that's a sign off a healthy
community - improving infrastructure and not just blindly holding on to the
old.

I guess I'll need to add it once I'm back from vacation.

**Comment by nuest** [comment]
Well, crantastic is _not_ and official repository, but a community driven site based on CRAN.

@bmaland @hadley can probably provide some perspective how to integrate best. IMHO it would be great if you could combine the statistics from both sources somehow..
