### ISSUE TITLE
Graphs for smaller repos are not working

### ISSUE THREAD

**Issue by hishamhm** [edebill/modulecounts#26]
Hi Erik,

(I'm the guy who submitted LuaRocks support. :) Thanks again for that!)

I noticed a problem in the graphic visualization. I tried enabling only the entries for repos with less than 10000 modules, and I notice that, of those, only Hackage and CRAN are plotting correctly. Crates.io (Rust), Hex.pm (Elixir/Erlang), LuaRocks (Lua) and Pear (PHP) are all graphing as constant zeros, if you enable them in the graph (at first I thought it was because of scale, but try enabling only these six I mentioned.

Thanks in advance!

**Comment by edebill** [comment]
Thanks for reporting this. I can reproduce it, and think I know what's up.

**Comment by edebill** [comment]
Fixed. The problem was a filter that tried to compensate for bad polling data with a hard coded cutoff. That worked great for bigger repos, but not for small ones. I've changed it to be a relative size comparison and it seems to be working fine now.
