### ISSUE TITLE
Feature: add drupal

### ISSUE THREAD

**Issue by oakley808** [edebill/modulecounts#27]
Would it be possible to add drupal to the mix?
https://www.drupal.org/project/project_module

**Comment by edebill** [comment]
Oh, cool! I didn't realize Drupal had it's own package system. I will try and add this next week, along with cocoapods.

**Comment by edebill** [comment]
Well, next week turned into several months, but this is up!

**Comment by oakley808** [comment]
Excellent! Thank you.
Heads up though, I see 404s on js/css assets here http://www.modulecounts.com/ (the graph isn't working)

**Comment by edebill** [comment]
Thank you! I was fooled by cached assets in my browser, but it's fixed now (again).
