### ISSUE TITLE
Feature: Add Perl 6

### ISSUE THREAD

**Issue by zoffixznet** [edebill/modulecounts#29]
Hey,

Would you be interested in adding [Perl 6 ecosystem](http://modules.perl6.org/) to the counts?

We've made a special link you can access to get the total count without parsing anything: http://modules.perl6.org/total

If something else will be easier for you, let me know and we'll implement it.

Cheers,
ZZ

**Comment by edebill** [comment]
Done.

**Comment by zoffixznet** [comment]
Awesome! Thanks a lot :smile_cat:
