### ISSUE TITLE
GoDoc.org no longer pulling counts

### ISSUE THREAD

**Issue by whereswaldon** [edebill/modulecounts#34]
The graph for GoDoc just seems to end mid-October and there are no counts for the last few days. Did the API there change or something?

**Comment by JesseAldridge** [comment]
It looks like the total package count is no longer displayed on that page.

Maybe https://gopm.io/ could be used instead?

**Comment by JesseAldridge** [comment]
http://go-search.org/ looks like it could work as well

**Comment by edebill** [comment]
I like that gopm.io seems like more of an intentional index, so closer in intent to all the others. The numbers won't line up well, so I think I'll stop polling for GoDoc and add gopm.io as a new repository. It should be done some time this week.

**Comment by JesseAldridge** [comment]
Cool, thanks.  It does seem strange that the numbers are so different -- 19K for gopm.io and 760K on Go Search.

**Comment by edebill** [comment]
GoDoc was known to do lots and lots of duplicate counts - it seemed to count forks as though they are separate items. It was not a good count, but it was the best I could find at the time. It probably holds the record for most complaints about including a repository.
