### ISSUE TITLE
Feature Request: Is it possible to add collection of a few more metrics....

### ISSUE THREAD

**Issue by jahagirdar** [edebill/modulecounts#38]
Along with the addition of new modules, is it possible to also collect metrics about module maintenance. e.g.

1. How many updated "new versions" of existing modules were released in a given week.
2. What is the average number of maintenance releases that have taken place for all modules in a given language.
3. For how many days/years after its first release is a module maintained in a given language (either has become stable or is abandoned )

The reason for asking these questions is, different languages and their repositories may have different culture.

1. An academic language/repository may see some amount of peer review and test for useful-ness before a new module is uploaded.
2. A 'hip' language might see 20 different modules for "downloading cat videos from facebook" by newbies learning the language and trying to create their professional portfolio...
3. A language backed by some major corporation might see ton's of updates to its modules as they get tested and bug fixed.
4. Another language might see hundreds of contributions from a single author with no updates to any of the modules after the first contribution...

**Comment by edebill** [comment]
I'd love to add all these statistics - they're all things I want to know and could be useful when you're making the case for using a new language.

Unfortunately I don't think it would be practical.

I generally have to rely on scraping websites for information each day, and delving into per-package level information would take too long and be incredibly brittle. Things already break any time a repository redesigns their website (or even changes the wording a little in some cases), and digging in for historical data would make that an order of magnitude worse. I'd also need to start paying for multiple worker processes to do the scraping, and I'm just not willing to do that. It would totally work if this was a commercial venture supporting a part time developer, but as it is I'm just not interested in taking on the additional work and expense.

Regards,
Erik

**Comment by andrew** [comment]
@jahagirdar we have quite a lot of that data available in https://libraries.io, much of which we've published as open data if you're interested in doing research work on it: https://zenodo.org/record/833207
